##### support vector machine

In [30]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

1. 목적: SVM을 가지고 iris 데이터를 분류해보자

2. 데이터 수집

In [31]:
df = load_iris()
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [32]:
x = df.data
y = df.target 

In [33]:
x = pd.DataFrame(x, columns = df.feature_names)
y = pd.DataFrame(y, columns = ['species'])

x와 y의 행의 개수가 동일한지 확인해주자

In [34]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [35]:
y

species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

3.데이터 전처리
- 스케일링
- 레이블 인코딩

In [36]:
#스케일링 함수 정의하기
transformer = MinMaxScaler()

#x데이터 학습시키기
transformer.fit(x)

MinMaxScaler()

In [37]:
#학습한 모델을 가지고 데이터 변환시키기-minmax값으로 변환?
x_data = transformer.transform(x)

x_data

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [38]:
#레이블 인코딩
le = LabelEncoder()

#정답값(y)에 대해학습
le.fit(y)
print(le.classes_)

[0 1 2]


c:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [39]:
#학습한 모델을 가지고 데이터 변환시키기
y_data = le.transform(y)
y_data

c:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [40]:
#훈련, 평가 데이터
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, random_state=0, stratify=y_data)

4.탐색적데이터분석(EDA)-클래스별 비율, 시각화

5.모델선택

In [41]:
#가우시안 커널 사용하는 svc 모델 선언               확률보기 위한 사전작업?
model = SVC(kernel = 'rbf', C=1.0, gamma='auto', probability = True)

6.모델학습

In [42]:
model.fit(x_train, y_train)

SVC(gamma='auto', probability=True)

7.모델평가

In [43]:
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.9464285714285714
0.9736842105263158


In [44]:
labels = ['세토사', '버시칼라', '버지니카']

- 새로운 데이터 예측

In [48]:
new_test = [[5.3, 3.7, 1.5, 0.2]]
new_test = pd.DataFrame(new_test, columns=['Sepal length', 'Sepal width', 'Petal length', 'Petal width'])

#스케일링
new_test = transformer.transform(new_test)

c:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Petal length
- Petal width
- Sepal length
- Sepal width
Feature names seen at fit time, yet now missing:
- petal length (cm)
- petal width (cm)
- sepal length (cm)
- sepal width (cm)

  warnings.warn(message, FutureWarning)


In [49]:
#예측하기
y_predict = model.predict(new_test)

In [50]:
label = labels[y_predict[0]]
print(label)

세토사
