In [1]:
import numpy as np
import pandas as pd

In [6]:
#1~50까지 짝수만 원소로 갖는 Numpy 배열 생성 - arrange 
arr = np.arange(2, 51, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


##### ones/zeros 의 결과값은 실수형이 기본

In [11]:
#0을 원소로 갖는 4*4 배열 생성
zero = np.zeros([4, 4])
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#1을 원소로 갖는 10*10 배열 생성
one = np.ones([10, 10])
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##### full은 내가 지정해준 값의 타입이 기본

In [13]:
#본인이 좋아하는 숫자를 원소로 갖는 7*4 배열 생성
mine = np.full([7, 4], 3)
mine

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [16]:
#1부터 100까지 원소 중 3의 배수를 원소로 갖는 넘파이 배열 생성
arr = np.arange(3, 100, 3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

- 만들어진 3의 배수를 원소로 갖는 넘파이 배열의 원소 개수를 구하고, reshape함수를 이용하여 2차원 배열을 생성하시오
- 생성된 2차원의 배열의 크기(shape)를 구하시오

In [26]:
print(arr.size)
arr2 = arr.reshape((3, 11))
print(arr2)
print(arr2.shape)

33
[[ 3  6  9 12 15 18 21 24 27 30 33]
 [36 39 42 45 48 51 54 57 60 63 66]
 [69 72 75 78 81 84 87 90 93 96 99]]
(3, 11)


##### Random

In [27]:
import random

1. 0~1사이의 값을 랜덤하게 가지는 6*4 배열을 생성하시오
2. 1~100 사이의 값을 램덤하게 가지는 5*5 배열을 생성하시오
3. astype을 사용하여 2번의 배열을 실수형태의 원소를 가지는 배열로 바꾸시오

In [28]:
#               난수 형태
arr = np.random.rand(6,4)
print(arr)

[[0.41012652 0.5667834  0.0915099  0.33818468]
 [0.61423511 0.53305127 0.03156967 0.15208298]
 [0.06749175 0.92407914 0.03612978 0.04318382]
 [0.42476899 0.9446734  0.18686843 0.93401129]
 [0.82575537 0.14591474 0.79747761 0.39154205]
 [0.19958319 0.86373227 0.25474738 0.45975447]]


In [39]:
#                  정수    범위     형태
arr_2 = np.random.randint(1, 100, (5, 5))
print(arr_2)

[[78 57 13 84 25]
 [15 27 84 16 19]
 [11 80 29 14 86]
 [73 52 17 17 65]
 [82 23 90 65 20]]


In [41]:
#실수형태로 변환 - .astype()
arr_float = arr_2.astype('float64')
arr_float

array([[78., 57., 13., 84., 25.],
       [15., 27., 84., 16., 19.],
       [11., 80., 29., 14., 86.],
       [73., 52., 17., 17., 65.],
       [82., 23., 90., 65., 20.]])

- 주어진 배열에서 3, 4, 8, 9 원소만 가져오기

In [53]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [52]:
x[:, 3:5]

array([[3, 4],
       [8, 9]])

- 주어진 배열에서 6, 7, 8 원소만 가져오기

In [55]:
x[1, 1:4]

array([6, 7, 8])

In [67]:
#주어진 행렬
print('=====================')
y=np.arange(15).reshape(3, 5)
print(y)
print('=====================')

#3, 8, 13 원소 가져오기
print(y[:, 3:4])
print('=====================')

#5, 6, 7, 8, 9 원소 가져오기
print(y[1:2, :])
print('=====================')

#1,2,3,6,7,8 원소 가져오기
print(y[0:2, 1:4])
print('=====================')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 3]
 [ 8]
 [13]]
[[5 6 7 8 9]]
[[1 2 3]
 [6 7 8]]


In [79]:
print('=====================')
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print('=====================')

#5보다 작거나 같은 값만 출력
print(arr[arr<=5])
print('=====================')

#3의 배수만 출력
print(arr[arr % 3 == 0])
print('=====================')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5]
[ 3  6  9 12]


##### %: AND, |: OR

In [89]:
print('=====================')
x=np.random.randint(1, 100, size=10)
print(x)
print('=====================')

#x에서 2의 배수만 추출하기
print(x[x % 2 == 0])
print('=====================')

#x에서 60이상의 수만 추출하기
print(x[x >= 60])
print('=====================')

#x에서 30보다 크고 70보다 작은 수만 출력
print(x[(x > 30) & (x < 70)])
print('=====================')

#x에서 60보다 크거나 홀수인 수를 출력
print(x[(x > 60) | ((x % 2 != 0))])
print('=====================')


[ 5 31 96 66 41 23 49 37 20  8]
[96 66 20  8]
[96 66]
[31 66 41 49 37]
[ 5 31 96 66 41 23 49 37]


- 2019년 7월 서울 기온 데이터
    - 기온이 25도를 넘는 날 수?
    - 기온이 25도를 넘는 날의 평균 기온은?

In [103]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
print(len(temp))

print("====기온이 25도를 넘는 날===")
temp_25 = temp[temp>25.0]
print(len(temp_25))
#np.sum(temp>25.0)

print("====기온이 25도를 넘는 날 수의 평균===")
#avg = sum(temp_25)/len(temp_25)
#print(avg)
print(np.mean(temp_25))


31
====기온이 25도를 넘는 날===
21
====기온이 25도를 넘는 날 수의 평균===
26.857142857142858
