In [1]:
import numpy as np
import pandas as pd
import random

In [22]:
data = np.loadtxt("ratings.txt", delimiter='::', dtype = 'int')

print("======================================================")
print(data)
print("======================================================")

#크기 확인
print(data.shape)
print("======================================================")

#차원 확인
print(data.ndim)
print("======================================================")

#원소 개수 확인
print(data.size)
print("======================================================")

#1번 아이디를 가진 사람의 정보만 출력
#               행 열
print(data[data[:, 0]==1])
print("======================================================")

#id 정보만 가져오기
id = data[:, 0]
print(id)
print("======================================================")

#전체 사용자 평점 평균 구하기
rating = data[:, 2]
print(rating)
print(np.mean(rating))
print("======================================================")

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
(1000209, 4)
2
4000836
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687    

##### 1번 사용자의 평점 평균 구하기

In [21]:
#1. ID정보 가져오기
print("======================================================")
id_1 =data[data[:, 0]==1]
print(id_1)
print("======================================================")

#2. 인덱싱한 자료에서 평점만 가져오기
rating_id1 = id_1[:, 2]
print(rating_id1)
print("======================================================")

#3. 가져온 평점 평균 구하기
print(rating_id1.mean())
print("======================================================")

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1