##### 정렬: sort

In [1]:
import numpy as np
import pandas as pd
import random

1. 1차원 정렬
- 1차원 정렬은 매우 간단
- sort 기능을 사용해도 저장은 되지 않는다. 저장하고 싶으면 새로운 변수에 할당해줘야한다.

In [9]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
print(arr)

#오름차순
print(np.sort(arr))

#내림차순
print(np.sort(arr)[::-1])

#새로운 변수에 정렬한 배열 할당
new_arr = np.sort(arr)
print(new_arr)

[ 1 10  5  8  2  4  3  6  8  7  9]
[ 1  2  3  4  5  6  7  8  8  9 10]
[10  9  8  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  8  9 10]


2. N차원 정렬

In [19]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])
print(arr2d)

#형태 확인
print(arr2d.shape)

#axis: 축 -> 가로축, 세로축을 0아니면 1로 표현

#열 정렬(왼쪽에서 오른쪽으로) -> 행을 기준으로?
new_add2d = np.sort(arr2d, axis=1)
print(new_add2d)


#행 정렬(위에서 아래로) ->열을 기준으로?
new2_add2d =np.sort(arr2d, axis=0)
print(new2_add2d)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
(3, 4)
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


##### y원소들의 평균, 합, 최대값, 최소값, 분산, 중앙값, 표준편차를 구해봅시다.

In [22]:
y = np.random.randint(100, size = (3, 5))
print(y)

[[ 1 31 16 65 62]
 [46  5 72 54 99]
 [78 79 39 39  6]]


In [31]:
#합계
print("합계: ", np.sum(y))

#평균
print("평균: ", np.mean(y))
#y.mean()

#최대값
print("최대값: ", y.max())

#최소값
print("최소값: ", y.min())

#분산
print("분산: ",y.var())

#중앙값
print("중앙값: ", np.median(y))

#표준편차
print("표준편차: ", y.std())

합계:  692
평균:  46.13333333333333
최대값:  99
최소값:  1
분산:  853.848888888889
중앙값:  46.0
표준편차:  29.220692820138417
